scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'localhost:8081', 'localhost:9100', 'localhost:9113', 'localhost:4200']

  - job_name: 'HospitalHub input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8081', 'localhost:9090']
        labels:
          application: "HospitalHub"